"""add proof of payment url to orders

Revision ID: d0d642dcdf55
Revises: 1549b4442ef4
Create Date: 2026-09-08 21:19:33.088070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d642dcdf55'
down_revision: Union[str, Sequence[str], None] = '1549b4442ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('proof_of_payment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'proof_of_payment_url')
    # ### end Alembic commands ###
